apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-practice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-practice-app
  template:
    metadata:
      labels:
        app: devops-practice-app
    spec:
      containers:
        - name: app
          image: chandana-devops-app:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
